"""Render a list of Ops as a runnable RouterOS .rsc patch."""

from __future__ import annotations

from datetime import datetime, timezone
from itertools import groupby

from .model import MENUS_SINGLETON, Op


def emit(ops: list[Op], *, header: str | None = None) -> str:
    lines: list[str] = []
    lines.append("# generated by rsc-diff")
    lines.append(f"# {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    if header:
        for hl in header.splitlines():
            lines.append(f"# {hl}")
    lines.append("")

    if not ops:
        lines.append("# no changes")
        return "\n".join(lines) + "\n"

    # Group consecutive ops by menu so we emit the menu path once.
    for menu, menu_ops in groupby(ops, key=lambda op: op.menu):
        lines.append(menu)
        for op in menu_ops:
            lines.append("    " + _render_op(op))
        lines.append("")

    return "\n".join(lines) + "\n"


def _render_op(op: Op) -> str:
    if op.kind == "add":
        return "add " + _render_props(op.props)

    if op.kind == "remove":
        return f"remove {_find_clause(op.menu, op.identity_key)}"

    # set
    if op.menu in MENUS_SINGLETON:
        # Singletons: bare `set prop=val ...`
        return "set " + _render_props(op.props)

    # Non-singleton set: `set [find ...] prop=val ...` (or positional id)
    selector = _find_clause(op.menu, op.identity_key)
    return f"set {selector} {_render_props(op.props)}"


def _render_props(props: dict[str, str]) -> str:
    """Render `key=value key2=value2 ...` preserving insertion order."""
    return " ".join(f"{k}={v}" for k, v in props.items())


def _find_clause(menu: str, identity_key: str) -> str:
    """Build the `[find ...]` (or positional) selector for an identity_key.

    identity_key formats produced by Item.identity_key():
      - "name=iac.x.y"          -> [find name=iac.x.y]
      - "comment~iac.x.y"       -> [find comment~"iac.x.y"]
      - "default-name=ether1"   -> [find default-name=ether1]
      - "@pos=N"                -> numbered (N) -- positional set
      - menu path itself        -> "" (singleton, no selector)
    """
    if identity_key == menu:
        return ""  # singleton

    if identity_key.startswith("@pos="):
        # Positional addressing: `set numbers=N prop=...`
        n = identity_key.split("=", 1)[1]
        return f"[find] numbers={n}"

    if identity_key.startswith("comment~"):
        token = identity_key.split("~", 1)[1]
        return f'[find comment~"{token}"]'

    # name= / default-name= / anything else key=value form
    return f"[find {identity_key}]"
