"""Menu classification used to drive identity resolution and diff strategy.

These sets carve the RouterOS menu universe into three behavioural groups.
A menu's classification determines how items under it are identified and
how the differ handles ordering / replacement.

Classifications
---------------
- :data:`MENUS_WITH_NAME` -- menus where ``name=`` is a user-set, stable
  identifier (not auto-generated by the router). Items in these menus key
  off ``name=``.
- :data:`MENUS_ORDERED` -- menus where item order is semantically
  significant (firewall chains evaluate top-to-bottom). The differ
  collapses any change in these menus to a wipe-then-add to avoid
  positional shift hazards.
- :data:`MENUS_SINGLETON` -- settings-blocks that hold a single implicit
  item; only ``set`` operations make sense. Identity is the menu path.

Adding a menu
-------------
Be conservative. A menu that's truly free-form (every row independent,
identity by ``name=`` or comment) doesn't need to appear here at all --
the parser falls back to comment-based identity, then position. List a
menu in :data:`MENUS_WITH_NAME` only after verifying that ``name=`` is
operator-settable on that menu (some menus have an auto-generated
``name`` you cannot change without recreating the row).
"""

from __future__ import annotations


# Menus where ``name=`` is the user-set identifier (not auto-generated).
# Items here use ``name=`` as their identity key when present.
MENUS_WITH_NAME: frozenset[str] = frozenset(
    {
        "/interface/list",
        "/interface/bridge",
        "/interface/wifi/datapath",
        "/interface/wifi/security",
        "/interface/wifi/channel",
        "/interface/wifi/configuration",
        "/ip/pool",
        "/ip/dhcp-server",
        # /ip/service rows have a stable user-visible `name` (the service
        # name itself: telnet, ssh, winbox, ...). Treating it as the
        # identity key keeps the differ stable when /export and authored
        # configs emit services in different orders.
        "/ip/service",
        "/system/script",
    }
)


# Menus where items are positional (rules in chains). Identity falls back
# to the comment, then to position. The differ collapses any non-trivial
# change in these menus to wipe-then-add.
MENUS_ORDERED: frozenset[str] = frozenset(
    {
        "/ip/firewall/filter",
        "/ip/firewall/nat",
        "/ip/firewall/mangle",
        "/ip/firewall/raw",
        "/ipv6/firewall/filter",
        "/ipv6/firewall/nat",
        "/ipv6/firewall/mangle",
        "/ipv6/firewall/raw",
    }
)


# Menus that are settings-blocks (single implicit item, only ``set`` makes
# sense). Identity is the menu path itself.
MENUS_SINGLETON: frozenset[str] = frozenset(
    {
        "/ip/dns",
        "/ip/neighbor/discovery-settings",
        "/system/clock",
        "/system/identity",
        "/disk/settings",
        "/tool/mac-server",
        "/tool/mac-server/mac-winbox",
        "/tool/mac-server/ping",
        "/system/routerboard/mode-button",
        "/system/routerboard/wps-button",
    }
)


# Token prefix for stable iac-namespace identifiers in ``name=`` or comments.
IAC_PREFIX = "iac."
