"""Render a list of Ops as a runnable RouterOS .rsc patch."""

from __future__ import annotations

from datetime import datetime, timezone
from itertools import groupby

from .model import MENUS_SINGLETON, Op


def emit(ops: list[Op], *, header: str | None = None) -> str:
    """Render *ops* as a runnable RouterOS ``.rsc`` patch.

    Groups consecutive ops by menu (so the menu path is emitted once per
    block), prepends a ``# generated by rsc-diff`` banner with timestamp
    and the optional *header* lines, and brackets any wipe-then-add
    block with ``# 1. REMOVE OLD`` / ``# 2. ADD NEW`` section comments.
    Empty *ops* produces a ``# no changes`` banner.
    """
    lines: list[str] = []
    lines.append("# generated by rsc-diff")
    lines.append(f"# {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    if header:
        for hl in header.splitlines():
            lines.append(f"# {hl}")
    lines.append("")

    if not ops:
        lines.append("# no changes")
        return "\n".join(lines) + "\n"

    # Group consecutive ops by menu so we emit the menu path once.
    for menu, menu_ops_iter in groupby(ops, key=lambda op: op.menu):
        menu_ops = list(menu_ops_iter)
        lines.append(menu)

        # Wipe-then-add pattern: when the first op in a menu is a wipe,
        # bracket it with REMOVE OLD / ADD NEW comments so the patch reads
        # as an intentional whole-menu replace.
        wipe_then_add = bool(menu_ops) and menu_ops[0].kind == "wipe"

        if wipe_then_add:
            lines.append("    # 1. REMOVE OLD")
            lines.append("    " + _render_op(menu_ops[0]))
            if len(menu_ops) > 1:
                lines.append("")
                lines.append("    # 2. ADD NEW")
                for op in menu_ops[1:]:
                    lines.append("    " + _render_op(op))
        else:
            for op in menu_ops:
                lines.append("    " + _render_op(op))
        lines.append("")

    return "\n".join(lines) + "\n"


def _render_op(op: Op) -> str:
    """Render a single :class:`Op` as one line of RouterOS script.

    Dispatch on ``op.kind``:
      - ``wipe``   -> ``remove [find dynamic=no]`` (skip system built-ins)
      - ``add``    -> ``add prop=val ...``
      - ``remove`` -> ``remove [find ...]``
      - ``reset``  -> ``reset [find ...] prop1 prop2 ...``
        (singletons emit bare ``reset prop1 ...``)
      - ``set``    -> ``set [find ...] prop=val ...``
        (singletons emit bare ``set prop=val ...``)
    """
    if op.kind == "wipe":
        # `dynamic=no` excludes system-protected built-in rules (e.g. the
        # `defconf:` entries RouterOS injects into firewall chains).
        # `remove [find]` would try to remove them too and fail with
        # `cannot remove builtin`, leaving the menu in a half-wiped
        # state. The operator-added rules we actually want to clear are
        # all dynamic=no.
        #
        # We use `dynamic=no` rather than the shorter `!dynamic` form
        # because the latter is rejected by some RouterOS versions'
        # script parser ("syntax error" inside the `[find ...]` body),
        # while `dynamic=no` is the documented and universally accepted
        # form for `find` queries.
        return "remove [find dynamic=no]"

    if op.kind == "add":
        return "add " + _render_props(op.props)

    if op.kind == "remove":
        return f"remove {_find_clause(op.menu, op.identity_key)}"

    if op.kind == "reset":
        # `reset` takes a list of property names, no values. It's the
        # documented RouterOS way to revert a property to its default
        # (see help.mikrotik.com/docs Console -> General Commands).
        prop_list = " ".join(op.props.keys())
        if op.menu in MENUS_SINGLETON:
            return f"reset {prop_list}"
        selector = _find_clause(op.menu, op.identity_key)
        return f"reset {selector} {prop_list}"

    # set
    if op.menu in MENUS_SINGLETON:
        # Singletons: bare `set prop=val ...`
        return "set " + _render_props(op.props)

    # Non-singleton set: `set [find ...] prop=val ...` (or positional id)
    selector = _find_clause(op.menu, op.identity_key)
    return f"set {selector} {_render_props(op.props)}"


def _render_props(props: dict[str, str]) -> str:
    """Render `key=value key2=value2 ...` preserving insertion order."""
    return " ".join(f"{k}={v}" for k, v in props.items())


def _find_clause(menu: str, identity_key: str) -> str:
    """Build the `[find ...]` (or positional) selector for an identity_key.

    identity_key formats produced by Item.identity_key():
      - "name=iac.x.y"          -> [find name=iac.x.y]
      - "comment~iac.x.y"       -> [find comment~"iac.x.y"]
      - "default-name=ether1"   -> [find default-name=ether1]
      - "@pos=N"                -> numbered (N) -- positional set
      - "@anon=N"               -> numbered (N) -- last-resort fallback for
                                   menus without a stable identity property
      - menu path itself        -> "" (singleton, no selector)
    """
    if identity_key == menu:
        return ""  # singleton

    # @pos / @anon are both internal positional selectors. RouterOS doesn't
    # know either token (`[find @anon=N]` raises "missing value for where"),
    # so render them via the documented `numbers=N` form. They differ only
    # in *why* the differ chose positional addressing -- semantically they
    # mean the same thing at apply time.
    if identity_key.startswith("@pos=") or identity_key.startswith("@anon="):
        n = identity_key.split("=", 1)[1]
        return f"[find] numbers={n}"

    if identity_key.startswith("comment~"):
        token = identity_key.split("~", 1)[1]
        return f'[find comment~"{token}"]'

    # name= / default-name= / anything else key=value form
    return f"[find {identity_key}]"
